swagger: 2.0
tags:
  - name: "status"
    description: "Set status"
schemes:
  - "http"
paths:
  /status/get:
    get:
      tags:
        - "status"
      summary: "Get status"
      description: ""
      operationId: "getStatus"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Member"
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
  /status/set:
    post:
      tags:
        - "status"
      summary: "Set status"
      description: ""
      operationId: "setStatus"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Set status"
          required: false
          schema:
            type: "object"
            properties:
              grade:
                type: "integer"
              class:
                type: "integer"
              number:
                type: "integer"
              status1:
                type: "integer"
              status2:
                type: "integer"
      responses:
        200:
          description: "OK"
        401:
          description: "Unauthorized"
        404:
          description: "Not Found"
        405:
          description: "Method Not Allowed"
        500:
          description: "Internal Server Error"
definitions:
  Member:
    type: "object"
    properties:
      grade:
        type: "integer"
      class:
        type: "integer"
      status:
        type: "array"
        items:
          type: "array"
          items:
            type: "integer"
    xml:
      name: "Member"
